### ISSUE TITLE
plugin don't active when i ticks it

### ISSUE THREAD

**Issue by Cherkah** [bittner/gedit-reST-plugin#13]
hi

your plugin might have be usefull fo me if it works . 
 i can't active the plugin. when i tick it i get a red cercle. wherever i put the  pyfile and its folder (user or global) the probleme is the same.

what's wrong?

distro: debian testing/gnome shell
gedit -v > 3.20

**Comment by bittner** [comment]
Have you tried the [gedit-3.14](https://github.com/bittner/gedit-reST-plugin/tree/gedit-3.14) branch? This may fix your situation. See also issue #12.

I should probably merge that branch into master, but from my point of view important features are missing, still broken or the plugin is generally not good enough to meet users' expectations. See issue #8 for a related discussion.

**Comment by bittner** [comment]
Ooops, I've just checked, and the branch is already merged into `master`.

* Can you run `gedit` from the Teminal and share the output in the error situations? (What is the exact error message?)
* Please also share the Python version (`python --version`, `python3 --version`)

**Comment by Cherkah** [comment]
output frome terminal:


- Traceback  (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/gedit/plugins/dashboard/__init__.py", line 58, in _add_tab
    [0].get_children()[0].get_children()[1].hide()
AttributeError: 'Image' object has no attribute 'get_children'

(gedit:7462): libpeas-WARNING **: Error importing plugin 'reST':
Traceback (most recent call last):
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'reST'

(gedit:7462): libpeas-WARNING **: Error loading plugin 'reST'

(gedit:7462): Gtk-WARNING **: Unable to parse accelerator '\u0002': ignored request to install 5 accelerators

- python -v : 3.5 and 2.7
python 2.7 as default to  the system

**Comment by bittner** [comment]
```
ImportError: No module named 'reST'
```
That sounds like an error that can be easily solved!

You need find out where a location is on your system that holds Python modules, which import correctly, and place the `reST.plugin` file and the `reST` folder there. Finding out [can be a bit tricky](http://stackoverflow.com/questions/122327/how-do-i-find-the-location-of-my-python-site-packages-directory) though.

Are you sure you have tried putting `reST` in the ` ~/.local/share/gedit/plugins/` folder?

**Comment by Cherkah** [comment]
thank,

my file/folder are in the local path **~/.local/share/gedit/plugins/ folder (user one)** yet, and  there are in some gedit's plugins wiche gives me no issues . as i said in my first msg i've tried "user and **global (/usr/lib/x86_64-linux-gnu/gedit/plugins)**" before to join you.
  can you point me out a location or should i give up rest-plugin?
thx

**Comment by bittner** [comment]
1. Please verify that the location you put both the `reST.plugin` file *and* the `reST` folder in really contains plugins that work with your installation of Gedit. (Not an unused copy)
1. The the import fails means that the plugin information as such is there(i.e. the plugin is found). But now the process of importing goes havoc. This suggests there are some files in the `rest/` folder or even the complete folder missing, so that Python fails to import for technical reasons.

Please double check those things.

**Comment by Cherkah** [comment]
ok bittner.
the library gir1.2-webkit-3.0. was missing.  
now i can tick the plugin in gedit and it works. 
 thanks  a lot for your patience.

regards

**Comment by bittner** [comment]
You're welcome! Glad it works for you.

If there is any other feedback you have on the plugin feel free to comment or open another issue.
