### ISSUE TITLE
Purpose of selection preview?

### ISSUE THREAD

**Issue by JanKanis** [bittner/gedit-reST-plugin#23]
One bug that's still remaining is that the preview doesn't update when the text selection changes. It shouldn't be extremely difficult to fix, just finding the right signals to listen to, but I don't really see the point of this feature. When I select something it is usually to copy it. And 90% of the time a selection of a reST document won't be valid reST itself or is just a few words of plain text. Do you know the purpose/use case of this feature? If not, what about taking it out?

**Comment by bittner** [comment]
You're actually right. We should take it out. It's an unnatural feature.

This feature is originally mentioned in the README. I [added it](https://github.com/bittner/gedit-reST-plugin/commit/197bd8be4d9121ee2a0867bc6c0d7d1be307037b) taking over the latest published version, published in a ZIP archive, hence putting the original author's work under version control. I later [reworded the description](https://github.com/bittner/gedit-reST-plugin/commit/2e6e909102ec13671b24747264706243bfeeffd8) of the feature, but this original meaning remained unchanged:

> If there's some selected text, the conversion will only process the selected portion of the text.
> If there's no selection, the entire document is processed. This may be useful for trouble shooting.

So, yes. Thumbs up for removing the feature. Please, go ahead!
