### ISSUE TITLE
Cannot get plugin to work in gedit - Version 3.14.3 (Fedora21 Testing)

### ISSUE THREAD

**Issue by anhsirksai** [bittner/gedit-reST-plugin#9]
I tried to setup reST plugin on *Fedora21.*
python version available: Python 3.4.1

Steps followed : 
### clone source and switch to gedit-3.14 branch
https://github.com/bittner/gedit-reST-plugin.git

### Install dependencies : 

pygments:
pip install pygments

docutils: (http://docutils.sourceforge.net/README.html#installation)
git clone git://repo.or.cz/docutils.git
cd docutils/docutils ; python3 setup.py install

odtwriter : could not find the source for this.

###  copy reST.plugin and reST/ into the path for edit plugins in fedora21: 
/usr/lib64/gedit/plugins

###  start gedit from terminal and load the plugin. I get the following error on terminal : 
[saikrishna@localhost plugins]$ gedit 
Traceback (most recent call last):
  File "/usr/lib64/gedit/plugins/reST/__init__.py", line 22, in <module>
    from .restructuredtext import RestructuredtextHtmlPanel
  File "/usr/lib64/gedit/plugins/reST/restructuredtext.py", line 20, in <module>
    from docutils.core import publish_parts
  File "/usr/lib/python3.4/site-packages/docutils/__init__.py", line 68, in <module>
    class ApplicationError(StandardError):
NameError: name 'StandardError' is not defined

(gedit:12392): libpeas-WARNING **: Error loading plugin 'reST'

Please suggest.

**Comment by bittner** [comment]
This seems to be an issue with [docutils](http://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/docutils/__init__.py#l68).

To help debugging, please say which version of docutils you are using (`pip freeze` should list the packages you're using). The version on the Debian system I'm using for issue #6 is `docutils==0.12`, Python version there is 3.4.2. That combination is working for the plugin.

Have you tried generating HTML from a reST file [from command line](http://docutils.sourceforge.net/docs/user/tools.html#html-generating-tools)? Does it work?

**Comment by anhsirksai** [comment]
Hi Bittnern

I have set it up successfully on my debian wheezy machine successfully. I am no longer going to test it on fedora any time soon. May be you may want to abandon this issue since I could not confirm you on further status! The other choice that made me abandon fixing this issue is https://github.com/ekalinin/github-markdown-toc. setting up markdown-toc is just running a script with and I am really have the way it is working.

Thanks,
--sai krishna.

**Comment by bittner** [comment]
Thanks for letting me know, @anhsirksai.

Sorry, I don't understand what the github-markdown-toc project has to do with reStructuredText and the Gedit plugin.

**Comment by anhsirksai** [comment]
I have added about that just to notify about a feature request(if possible)
for gedit-reST-plugin. the github-markdown-toc plugin has a shell script
which when run, will install the plugin and I felt it is easy to use
without much of a hassle.

I haven't done a comparative study on functioning of both these plugins
yet. So I have nothing to comment on working of either plugin.

Thank you,
--sai krishna.
